# numpy

In [1]:
import numpy as np
import random as r

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [7]:
#traditional python list 
list1=[10,20,30]
list2=[1,2,3]

In [ ]:
#to add 2 lists

In [16]:
list1+list2

[10, 20, 30, 1, 2, 3]

In [8]:
type(list1)

list

In [10]:
#numpy 
lst1= np.array([10,20,30])
lst2= np.array([1,2,3])


In [12]:
type(lst1)

numpy.ndarray

In [13]:
print(lst1)

[10 20 30]


In [18]:
lst3=lst1+lst2

In [19]:
type(lst3)

numpy.ndarray

In [21]:
#sequence numbers
#sequence of numbers from 0
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
#sequence from 1-9 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#sequence from 1-20 with a differnce of 5
arr1=np.arange(1,21,5)
arr1

array([ 1,  6, 11, 16])

In [26]:
#add  10 to every element of arr1 
arr1+10

array([11, 16, 21, 26])

In [28]:
#square of numbers
arr1**2   #dtype=int32 ..... it acn take only int 

array([  1,  36, 121, 256], dtype=int32)

In [ ]:
#4types of datatupe int32,64 , float32,64

In [30]:
min(arr1)

1

In [35]:
#difference in excution time in between puthon and numpy
#python code
num=range(1,1001)
%timeit [i**2 for i in num]

285 µs ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
#numpy code
numpy1=np.arange(1,1001)
%timeit numpy1**2

1.17 µs ± 35.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [36]:
#concatenate numpy
arr1 = np.arange(1,11,3)
arr2 = np.arange(5,23,6)

In [37]:
arr1

array([ 1,  4,  7, 10])

In [38]:
arr2

array([ 5, 11, 17])

In [40]:
arr3 = np.concatenate([arr1,arr2])
arr3

array([ 1,  4,  7, 10,  5, 11, 17])

In [43]:
#append values 
arr3=np.append(arr3,np.arange(50,70,5))
print(arr3)

[ 1  4  7 10  5 11 17 50 55 60 65]


In [44]:
#python list / tuples can be converted to np
num1 = [11,15,20,25] 

In [45]:
type(num1)

list

In [47]:
num1=np.asarray(num1,dtype=np.int32)

In [48]:
print(num1)

[11 15 20 25]


In [49]:
type(num1)

numpy.ndarray

In [50]:
#tuple
num2 = (1,2,3,4)
type(num2)


tuple

In [51]:
num2=np.asarray(num2)
type(num2)

numpy.ndarray

In [55]:
#calculate area of circle where nump2 represents the radius 
##pi*r^2
np.round(np.pi*num2*num2,2)

array([ 3.14, 12.57, 28.27, 50.27])

In [ ]:
#random number generation
#1)integer
#2)float

In [58]:
#1)integer
rint1 = np.random.randint(10,50,20)
rint1

array([31, 41, 34, 44, 11, 12, 43, 46, 45, 15, 37, 21, 36, 17, 13, 11, 37,
       38, 18, 25])

In [59]:
np.sort(rint1)

array([11, 11, 12, 13, 15, 17, 18, 21, 25, 31, 34, 36, 37, 37, 38, 41, 43,
       44, 45, 46])

In [60]:
#descending sort
-1*np.sort(-rint1)

array([46, 45, 44, 43, 41, 38, 37, 37, 36, 34, 31, 25, 21, 18, 17, 15, 13,
       12, 11, 11])

In [61]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [ ]:
#seed function equivalent in np

In [62]:
#get the index positions of all values greater than 30
np.where(rint1>30)

(array([ 0,  1,  2,  3,  6,  7,  8, 10, 12, 16, 17], dtype=int64),)

In [63]:
#actual values matching the conditions
rint1[np.where(rint1>30)]

array([31, 41, 34, 44, 43, 46, 45, 37, 36, 37, 38])

In [66]:
#get all odd numbers from array 
rint1[np.where(rint1%2>0)]

array([31, 41, 11, 43, 45, 15, 37, 21, 17, 13, 11, 37, 25])

In [68]:
#fancy indexing 
#get all numbers divisible by 3
mask = (rint1%3==0)
rint1[mask]

array([12, 45, 15, 21, 36, 18])

In [ ]:
#convert 1-D to n-D


In [72]:
arr4= np.random.randint(1,51,20)
arr4


array([47, 20, 45,  8,  2, 33, 43, 32,  5, 50, 12, 50, 29, 22, 31, 34,  2,
       12, 50, 22])

In [73]:
arr4.shape

(20,)

In [76]:
arr4 = arr4.reshape(5,4)

In [78]:
print(arr4)

[[47 20 45  8]
 [ 2 33 43 32]
 [ 5 50 12 50]
 [29 22 31 34]
 [ 2 12 50 22]]


In [79]:
arr4.shape

(5, 4)

In [80]:

arr4[0]    #row1

array([47, 20, 45,  8])

In [81]:
arr4[0,1]#R=0,C=1

20

In [82]:
#Change balue in array 
arr4[0,0]=100

In [83]:
arr4

array([[100,  20,  45,   8],
       [  2,  33,  43,  32],
       [  5,  50,  12,  50],
       [ 29,  22,  31,  34],
       [  2,  12,  50,  22]])

In [84]:
#create data and change dimensions in a single line 
arr5 = np.random.randint(10,101,15).reshape(5,3)
arr5

array([[98, 76, 41],
       [38, 50, 92],
       [66, 12, 82],
       [74, 34, 61],
       [81, 33, 21]])

In [85]:
#how to make the dimensions dynamic by specifying the R or C as -1
arr5= np.random.randint(10,101,30).reshape(-1,3)

arr5

array([[39, 13, 10],
       [69, 76, 89],
       [90, 64, 20],
       [11, 19, 17],
       [66, 54, 61],
       [56, 57, 77],
       [74, 41, 71],
       [11, 86, 57],
       [35, 59, 56],
       [99, 70, 35]])

In [86]:
arr6 = np.random.randint(1,100,40).reshape(10,-1)
arr6

array([[49, 17, 25, 39],
       [24, 74, 92, 73],
       [52, 26, 86, 39],
       [16,  2, 39, 46],
       [62, 38, 21, 82],
       [11, 28, 36,  8],
       [56, 40, 34, 94],
       [22, 85, 16, 33],
       [22, 36, 92, 52],
       [10, 71, 41, 97]])

In [88]:
np.where(arr6>70)

(array([1, 1, 1, 2, 4, 6, 7, 8, 9, 9], dtype=int64),
 array([1, 2, 3, 2, 3, 3, 1, 2, 1, 3], dtype=int64))

In [90]:
#2)float
#always between 0-1
#1)
prob1 = np.round(np.random.ranf(5),2)
prob1                                              #0-1   <--range

array([0.47, 0.21, 0.7 , 0.99, 0.79])

In [92]:
#2)
np.round(np.random.random(10),3).reshape(-1,2)

array([[0.497, 0.156],
       [0.912, 0.472],
       [0.522, 0.217],
       [0.148, 0.007],
       [0.873, 0.03 ]])

In [93]:
#between any 2 numbers
np.round(np.random.uniform(1,50,30),2)

array([45.99, 11.77, 47.03,  3.21, 38.68, 23.98, 28.76, 19.58, 34.36,
        6.48, 22.07, 26.77,  6.91, 47.06, 45.6 , 22.62, 11.67, 23.89,
        6.27, 18.16,  6.87, 25.18, 31.36, 16.93, 34.51, 19.85, 15.91,
       30.84, 38.7 , 40.57])

In [95]:
#sequence between 2 floats
np.round(np.linspace(1,5,10),2)

array([1.  , 1.44, 1.89, 2.33, 2.78, 3.22, 3.67, 4.11, 4.56, 5.  ])

In [96]:
#create unique values 
#selection without replacement 
arr7 = np.random.choice(np.arange(1,21),15,replace=False)
arr7

array([ 1,  3, 20,  4, 14, 19,  2, 15,  7,  9, 13, 12,  6,  8, 16])

In [97]:
np.sort(arr7)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20])

In [ ]:
#pre-defined arrays  ->that you cAN USE TO INITIAl value or any array
#1)np.empty
#2)np.zeros
#3)np.ones


In [107]:
#1)np.empty
#create mxn array and initialise with random values(can also specify data type)
np.empty([3,4],np.int16)


array([[  1,   0,   0,   0],
       [  0,   0,   0,   0],
       [  1,   0, 753,   0]], dtype=int16)

In [105]:
np.empty([3,4],np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [100]:
#2)np.zeros
#create mxn array and initialise with 0
np.zeros([2,3],np.int32)



array([[0, 0, 0],
       [0, 0, 0]])

In [115]:
np.zeros([3,5],np.float32)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
#3)np.ones
#create mxn array and initialise with 1

In [116]:
np.ones([2,2],np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [117]:
np.ones([3,3],np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [119]:
#create any array to store the marks of 20 students :each student has has given 5 tests
#score ->1-100
#number of subjects are fixed
marks = np.random.randint(1,101,100).reshape(-1,5)
marks

array([[59, 18, 80, 93, 60],
       [31, 12, 57, 10,  5],
       [85, 72, 22, 91, 72],
       [26, 35, 14, 60, 79],
       [11, 42, 51, 11, 91],
       [20, 82, 95,  8, 42],
       [52, 31, 58, 48, 41],
       [43, 64, 90, 55, 51],
       [91, 15, 75, 41, 54],
       [25, 57, 52, 69,  1],
       [57, 44, 25, 67, 77],
       [29, 20, 60, 77, 74],
       [92,  6, 20, 42, 45],
       [49, 50, 60, 99, 67],
       [77, 55, 93, 12, 60],
       [69, 81, 54, 30, 25],
       [70, 76, 96, 72,  9],
       [55,  7, 31, 53, 93],
       [68, 48,  2, 42, 62],
       [85, 99, 46, 43, 46]])

In [120]:
#operations on  array
#statistical ops can be done in 3 ways
#1) on the entire array
#2)row wise
#3)column wise
#entire array
np.max(marks)    #highest        


99

In [121]:
np.min(marks)   #lowest

1

In [122]:
np.mean(marks)  #average

51.66

In [123]:
np.std(marks)  #standard dev

26.70813359259684

In [124]:
np.median(marks)  # median

53.5

In [125]:
np.sum(marks)     #sum total

5166

In [126]:
#row wise (axis=1)
np.max(marks,axis=1)  #highest score ,rowwise

array([93, 57, 91, 79, 91, 95, 58, 90, 91, 69, 77, 77, 92, 99, 93, 81, 96,
       93, 68, 99])

In [127]:
np.min(marks,axis =1)  #lowest score ,rowwise

array([18,  5, 22, 14, 11,  8, 31, 43, 15,  1, 25, 20,  6, 49, 12, 25,  9,
        7,  2, 43])

In [128]:
np.mean(marks,axis=1)    #average of each student

array([62. , 23. , 68.4, 42.8, 41.2, 49.4, 46. , 60.6, 55.2, 40.8, 54. ,
       52. , 41. , 65. , 59.4, 51.8, 64.6, 47.8, 44.4, 63.8])

In [129]:
#column wise (axis=0)
np.max(marks,axis=0)  #highest score ,columnwise

array([92, 99, 96, 99, 93])

In [130]:
np.min(marks,axis =0)  #lowest score ,columnwise

array([11,  6,  2,  8,  1])

In [131]:
np.mean(marks,axis=0)    #average of each student

array([54.7 , 45.7 , 54.05, 51.15, 52.7 ])

In [138]:
# 1-d array and to extract numbers falling within a range eg: 50-60
num1=np.random.randint(25,101,50)
num1

array([64, 37, 84, 78, 43, 40, 72, 80, 87, 55, 89, 57, 45, 59, 91, 28, 55,
       94, 60, 85, 67, 94, 74, 85, 25, 32, 64, 74, 71, 98, 55, 59, 74, 91,
       31, 72, 82, 91, 58, 95, 93, 89, 77, 29, 76, 76, 76, 85, 84, 67])

In [139]:
len(num1)

50

In [140]:
#1)
num1[(num1>49)&(num1<61)]

array([55, 57, 59, 55, 60, 55, 59, 58])

In [142]:
%timeit num1[(num1>49)&(num1<61)]

2.25 µs ± 88.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [141]:
#2)
num1[np.where((num1>49)&(num1<61))]


array([55, 57, 59, 55, 60, 55, 59, 58])

In [143]:
%timeit num1[np.where((num1>49)&(num1<61))]

2.96 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [144]:
#array broadcast
marks= np.random.randint(1,101,20).reshape(-1,4)
wt=np.array([0.25,0.15,0.40,0.2])

In [145]:
#calculate weighted avg
marks*wt

array([[15.5 ,  0.3 , 31.2 , 16.  ],
       [21.25,  9.3 ,  7.2 ,  9.8 ],
       [ 8.  ,  8.25, 40.  ,  5.6 ],
       [21.5 , 13.05, 34.8 ,  5.8 ],
       [12.25,  2.85,  0.8 ,  9.2 ]])

In [146]:
#find the weighted average of each student
np.sum(marks*wt,axis=1)

array([63.  , 47.55, 61.85, 75.15, 25.1 ])

In [147]:
#set operations 
arr1 = np.random.randint(1,21,5)
arr1

array([ 2,  7,  5, 13,  9])

In [152]:
arr2 = np.random.randint(1,21,5)
arr2

array([ 2,  6, 18,  8, 15])

In [153]:
#union
#horizontal stack/concatenate
np.hstack([arr1,arr2])   

array([ 2,  7,  5, 13,  9,  2,  6, 18,  8, 15])

In [154]:
#vertical stack
np.vstack([arr1,arr2])   

array([[ 2,  7,  5, 13,  9],
       [ 2,  6, 18,  8, 15]])

In [156]:
#intersection
np.intersect1d(arr1,arr2)

array([2])

In [157]:
#difference 
#A-B(all elements of A NOT IN B)
np.setdiff1d(arr1,arr2)    #follow the rules of set

array([ 5,  7,  9, 13])

In [158]:
#B-A(all elements of B NOT IN A)
np.setdiff1d(arr2,arr1)

array([ 6,  8, 15, 18])

In [159]:
#repeat 
seq = np.array([1,2,3])
np.repeat(seq,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [160]:
#repeats each number in the sequence 3 times
np.tile(seq,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [164]:
#shuffle
#create a sequence 3 times
city = np.array(['pune','mumbai','chennai'])
city

array(['pune', 'mumbai', 'chennai'], dtype='<U7')

In [165]:
city= np.repeat(city,10)
city

array(['pune', 'pune', 'pune', 'pune', 'pune', 'pune', 'pune', 'pune',
       'pune', 'pune', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai',
       'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'chennai',
       'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai',
       'chennai', 'chennai', 'chennai'], dtype='<U7')

In [169]:
#random shuffle
np.random.shuffle(city)

In [170]:
city

array(['chennai', 'mumbai', 'pune', 'mumbai', 'pune', 'pune', 'chennai',
       'chennai', 'pune', 'pune', 'mumbai', 'mumbai', 'chennai',
       'chennai', 'pune', 'mumbai', 'chennai', 'mumbai', 'chennai',
       'mumbai', 'pune', 'mumbai', 'pune', 'chennai', 'mumbai', 'pune',
       'chennai', 'pune', 'chennai', 'mumbai'], dtype='<U7')

In [171]:
#array transpose 
arr4

array([[100,  20,  45,   8],
       [  2,  33,  43,  32],
       [  5,  50,  12,  50],
       [ 29,  22,  31,  34],
       [  2,  12,  50,  22]])

In [172]:
arr4.T

array([[100,   2,   5,  29,   2],
       [ 20,  33,  50,  22,  12],
       [ 45,  43,  12,  31,  50],
       [  8,  32,  50,  34,  22]])

In [174]:

arr1

array([ 2,  7,  5, 13,  9])

In [175]:

#order
#returns the location of the smallest->highest index from the array
np.argsort(arr1)   #

array([0, 2, 1, 4, 3], dtype=int64)

In [ ]:
#rank(lowest score = hoghest rank)
#arr1 = np.sort(arr1)
#np.argsort(arr1)

In [ ]:
#arr1 = -1*np.sort(-arr1)
#arr1
#np.argsort(arr1)

In [176]:
#to get the rank ,sort the result of argsort
print(dir(np),end ='')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes